name = "Isabelle"
grammar = "isabelle"
path_suffixes = ["thy"]

block_comment = { start = "(*", prefix = "", end = "*)", tab_size = 1 }

brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
]
